### ISSUE TITLE
Feature request: Interrogate CLIP and Interrogate DeepBooru for koishi-novelai-bot and SD-Webui users

### ISSUE THREAD

**Issue by kuyin** [MirrorCY/sd-switch#2]
Feature request: Add a interrogate function based on API of Interrogate CLIP and Interrogate DeepBooru in Stable Diffusion WebUI
Name suggestion: sd-interroage
Function name suggestion: interrogate, intrg
Console inputs suggestion: endpoint, headers, max words return, default method(DeepBooru or CLIP)

Just do it. :-)

**Comment by MirrorCY** [comment]
已完成，插件市场搜索 `sd-interroage`
