### ISSUE TITLE
希望能加个切换lora功能&切换vae有点bug

### ISSUE THREAD

**Issue by yi03** [MirrorCY/sd-switch#3]
~~最近lora很火，我也觉得很好用，希望能加个lora切换功能。
https://github.com/kohya-ss/sd-webui-additional-networks
安装这个插件后能在stable diffusion webui上使用lora。
https://civitai.com/?query=LORA
这里有一些lora模型可以下载。~~
不需要了，我发现stable diffusion webui的prompt里直接写lora:amberGenshinImpact_flexibleV1:1就可以直接调用相应的lora模型了，不需要手动选择模型。

还有切换vae现在有bug。虽然我现在暂时也不需要切换vae了，因为我发现现在所有的novelai衍生模型都是用的同一个vae。
![QQ截图20230125111552](https://user-images.githubusercontent.com/32034998/214472359-b15ac8f7-5ec5-49f9-ba1c-29eb92a623f0.png)

**Comment by yi03** [comment]
不对，我发现stable diffusion webui的prompt里直接写<lora:amberGenshinImpact_flexibleV1:1>就可以直接调用相应的lora模型了，不需要手动选择模型。

**Comment by MirrorCY** [comment]
可以具体描述一下 bug 吗

**Comment by yi03** [comment]
> 可以具体描述一下 bug 吗

本地目录下有3个VAE模型，但是bot回复的显示一个VAE模型也没有。一个月前使用插件时切换VAE是没问题的。

**Comment by MirrorCY** [comment]
曾经可以显示但现在不显示了？听起来挺奇怪的

**Comment by MirrorCY** [comment]
检查此处的输入
![image](https://user-images.githubusercontent.com/37006258/214494204-7ee51eec-269b-404c-8830-c409489fc2da.png)

**Comment by yi03** [comment]
> 曾经可以显示但现在不显示了？听起来挺奇怪的

猜想可能是因为stable diffusion webui改了前端？我的插件和stable diffusion webui都是最新版。

**Comment by yi03** [comment]
> 检查此处的输入 ![image](https://user-images.githubusercontent.com/37006258/214494204-7ee51eec-269b-404c-8830-c409489fc2da.png)

添加了vaeList后可以正常切换vae了，感谢。
我没仔细看插件配置项，不好意思。那我没什么问题了。

**Comment by MirrorCY** [comment]
嗷，现在需要手动输入，因为 sdapi 没有给出获取 vae list 的接口（或者我没找到
如果有人发现 sd 更新了此功能可以提醒我，我会第一时间更新。
